apiVersion: v2
name: follytics
version: 0.0.1
dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 16.7.19
    repository: https://charts.bitnami.com/bitnami
  - name: opentelemetry-collector
    version: 0.127.2
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
  - name: tempo
    version: 1.23.2
    repository: https://grafana.github.io/helm-charts
    condition: tempo.enabled
  - name: loki
    version: 6.32.0
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 27.26.0
    condition: prometheus.enabled
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    version: 9.2.10
    condition: grafana.enabled
  - name: application
    condition: api.enabled
    alias: api
    version: 6.5.0
    repository: https://stakater.github.io/stakater-charts
  - name: application
    condition: worker.enabled
    alias: worker
    version: 6.5.0
    repository: https://stakater.github.io/stakater-charts
  - name: application
    condition: ui.enabled
    alias: ui
    version: 6.5.0
    repository: https://stakater.github.io/stakater-charts
