version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    pull-request-branch-name:
      separator: '/'
    commit-message:
      prefix: 'chore: '

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: '/'
    commit-message:
      prefix: 'chore: '

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: '/'
    commit-message:
      prefix: 'chore: '

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: '/'
    commit-message:
      prefix: 'chore: '

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: '/'
    commit-message:
      prefix: 'chore: '
