version: "2"

run:
  concurrency: 4
  modules-download-mode: readonly
  issues-exit-code: 2
  allow-parallel-runners: true

output:
  formats:
    tab:
      path: stdout

linters:
  default: all
  disable:
    - exhaustruct

  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - $gostd
          deny:
            - pkg: math/rand$
              desc: use math/rand/v2
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package

    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print(|f|ln)|print|println)$
        - pattern: ^(repository\.)?WithDebug$

#    godox:
#      keywords:
#        - '@todo'

    varnamelen:
      min-name-length: 2
      ignore-names:
        - i
      ignore-type-assert-ok: true
      ignore-map-index-ok: true
      ignore-chan-recv-ok: true

    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - gorm.io\/gorm\/logger\.Interface
        - gorm.io\/gorm\/clause\.Expression

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - prefix(github.com/abgeo/follytics)

  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
