run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-tab

linters-settings:
  varnamelen:
    min-name-length: 2
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - i

  gci:
    sections:
      - standard
      - default
      - prefix(github.com/abgeo/follytics)
    skip-generated: false
    custom-order: true

  depguard:
    rules:
      main:
        list-mode: lax
        allow:
          - $gostd
        deny:
          - pkg: 'math/rand$'
            desc: use math/rand/v2
          - pkg: 'github.com/pkg/errors'
            desc: Should be replaced by standard lib errors package

  godox:
    keywords:
      - '@todo'

  forbidigo:
    forbid:
      - "^(fmt\\.Print(|f|ln)|print|println)$"
      - "^(repository\\.)?WithDebug$"

linters:
  enable-all: true
  disable:
    - exhaustruct

    # Deprecated.
    - exportloopref
