services:
  traefik:
    image: 'traefik:v3.5'
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.file.filename=/config.yaml'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - './traefik.yaml:/config.yaml:ro'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    networks:
      main:
        ipv4_address: 172.20.0.2
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: 'postgres:17.5'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: follytics
      POSTGRES_USER: follytics
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U follytics' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      main:
        ipv4_address: 172.20.0.3

  otel-lgtm:
    image: 'grafana/otel-lgtm:0.11.6'
    volumes:
      - 'otel_lgtm_data:/data'
    networks:
      main:
        ipv4_address: 172.20.0.4
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.otel_lgtm_grafana.rule=Host(`grafana.follytics.localhost`)"
      - "traefik.http.services.otel_lgtm_grafana.loadbalancer.server.port=3000"

volumes:
  postgres_data:
    driver: local
  otel_lgtm_data:
    driver: local

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/28
