env: prod

logger:
  level: info
  format: json

server:
  address: 0.0.0.0
  port: 8000
  trusted_proxies: []

cors:
  enabled: true
  allow_origins: ["*"]
  allow_methods: ["POST", "GET"]
  allow_headers: ["Origin", "Authorization"]
  expose_headers: ["Content-Length"]
  allow_credentials: false
  max_age: 12h

swagger:
  enabled: false
  path: /swagger

healthcheck:
  enabled: true
  path: /healthz

database:
  host: 172.20.0.3
  port: 5432
  user: follytics
  password: password
  database: follytics
  batch_size: 100
  skip_default_transaction: true

database_migrator:
  migrations_path: /var/migrations
  atlas_binary_path: atlas

github:
  app_client_id:
  app_private_key_path:
  app_installation_id:
  jwt_expiration: 1

worker:
  job:
    sync_followers:
      batch_size: 10
      github_page_size: 100
      github_rate_limit_threshold: 100

telemetry:
  enabled: false
  collector_url: 127.0.0.1:4317
