http:
  routers:
    api:
      rule: "Host(`api.follytics.localhost`)"
      service: api
    front:
      rule: "Host(`follytics.localhost`)"
      service: front

  services:
    api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8000"
    front:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3000"
