npmName: 'sdk'
npmVersion: 0.0.0
axiosVersion: ^1.9.0
licenseName: MIT
supportsES6: true
ensureUniqueParams: true
disallowAdditionalPropertiesIfNotPresent: false
useSingleRequestParameter: true
withSeparateModelsAndApi: true
apiPackage: api
modelPackage: model
