/* tslint:disable */
/* eslint-disable */
/**
 * Follytics API
 * Follytics API service
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@follytics.localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMetadata } from './pagination-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { ResponseEventWithUserReference } from './response-event-with-user-reference';
// May contain unused imports in some cases
// @ts-ignore
import type { ResponseHTTPResponseArrayResponseEventWithUserReference } from './response-httpresponse-array-response-event-with-user-reference';

/**
 * @type GetUserFollowEvents200Response
 * @export
 */
export type GetUserFollowEvents200Response = ResponseHTTPResponseArrayResponseEventWithUserReference;


