/* tslint:disable */
/* eslint-disable */
/**
 * Follytics API
 * Follytics API service
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@follytics.localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResponseUser
 */
export interface ResponseUser {
    /**
     * 
     * @type {string}
     * @memberof ResponseUser
     */
    'avatar': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseUser
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseUser
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseUser
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseUser
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseUser
     */
    'username': string;
}

