/* tslint:disable */
/* eslint-disable */
/**
 * Follytics API
 * Follytics API service
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@follytics.localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResponseHTTPError
 */
export interface ResponseHTTPError {
    /**
     * 
     * @type {string}
     * @memberof ResponseHTTPError
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof ResponseHTTPError
     */
    'message': string;
}

