/* tslint:disable */
/* eslint-disable */
/**
 * Follytics API
 * Follytics API service
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@follytics.localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ResponseUser } from './response-user';

/**
 * 
 * @export
 * @interface ResponseHTTPResponseArrayResponseUser
 */
export interface ResponseHTTPResponseArrayResponseUser {
    /**
     * 
     * @type {Array<ResponseUser>}
     * @memberof ResponseHTTPResponseArrayResponseUser
     */
    'data': Array<ResponseUser>;
}

