/* tslint:disable */
/* eslint-disable */
/**
 * Follytics API
 * Follytics API service
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@follytics.localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ResponseFollowersTimelineItem
 */
export interface ResponseFollowersTimelineItem {
    /**
     * 
     * @type {string}
     * @memberof ResponseFollowersTimelineItem
     */
    'date': string;
    /**
     * 
     * @type {number}
     * @memberof ResponseFollowersTimelineItem
     */
    'follows': number;
    /**
     * 
     * @type {number}
     * @memberof ResponseFollowersTimelineItem
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof ResponseFollowersTimelineItem
     */
    'unfollows': number;
}

