{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-grafana-datasource
  labels:
    {{ $.Values.grafana.sidecar.datasources.label }}: {{ $.Values.grafana.sidecar.datasources.labelValue | quote }}
    app: {{ .Release.Name }}-grafana
data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      {{if .Values.prometheus.enabled -}}
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: $PROMETHEUS_URL
        jsonData:
          httpMethod: POST
        editable: true
      {{ end }}
      {{- if .Values.loki.enabled -}}
      - name: Loki
        type: loki
        uid: loki
        url: $LOKI_URL
        access: proxy
        editable: true
      {{ end }}
      {{- if .Values.tempo.enabled -}}
      - name: Tempo
        type: tempo
        uid: tempo
        url: $TEMPO_URL
        access: proxy
        editable: true
      {{ end }}
{{ end }}
